# Generated by Django 4.1.8 on 2023-04-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentIndustryApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobApplicants',
        ),
        migrations.AlterField(
            model_name='students',
            name='behance',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='students',
            name='github',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='students',
            name='linkedin',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='students',
            name='roll',
            field=models.CharField(max_length=8),
        ),
    ]
